name: rtg
favicon: null
layout_spectrum: 0.51035
typography_spectrum: 0.36607
title: roetgers.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333541'
    - '#f7d1be'
    - '#6d7276'
    - '#8aacc8'
  brandStrength: 0.75
  lightness: 0.859415072016418
  saturation: 0.3564215775113553
  rhythmicContrast: 0.47838536999188364
purpose: []
