name: rtg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36756
title: roetgers.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69840209-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#093759'
    - '#010127'
    - '#388188'
    - '#9cc7b3'
    - '#fbffe4'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.47838536999188364
purpose: []
