typography_spectrum: 0.40486
color:
  brandColors:
    - '#093759'
    - '#010127'
    - '#388188'
    - '#9cc7b3'
    - '#fbffe4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.47838536999188364
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-69840209-1
  facebook: null
  twitter: null
author:
  name: Mike Rötgers
  email: mike@roetgers.org
  url: roetgers.org
name: rtg
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: roetgers.org
purpose: []
